MVP_WORKFLOW_ROLES = ("System Manager", "3PL Warehouse Manager", "3PL Warehouse User")
MVP_WORKFLOWS = [
    {
        "name": "3PL Inbound Shipment Notice Workflow",
        "document_type": "Inbound Shipment Notice",
        "states": ["Draft", "In Verification", "Partially Received", "Discrepancy Review", "Received", "Closed"],
        "client_edit_states": ["Draft"],
        "transitions": [
            ("Draft", "Submit to Warehouse", "In Verification", ("3PL Client", *MVP_WORKFLOW_ROLES)),
            ("Draft", "Mark Partially Received", "Partially Received", MVP_WORKFLOW_ROLES),
            ("Draft", "Request Client Review", "Discrepancy Review", MVP_WORKFLOW_ROLES),
            ("Draft", "Mark Received", "Received", MVP_WORKFLOW_ROLES),
            ("Draft", "Close", "Closed", MVP_WORKFLOW_ROLES),
            ("In Verification", "Mark Partially Received", "Partially Received", MVP_WORKFLOW_ROLES),
            ("In Verification", "Request Client Review", "Discrepancy Review", MVP_WORKFLOW_ROLES),
            ("In Verification", "Mark Received", "Received", MVP_WORKFLOW_ROLES),
            ("In Verification", "Return to Draft", "Draft", MVP_WORKFLOW_ROLES),
            ("Partially Received", "Request Client Review", "Discrepancy Review", MVP_WORKFLOW_ROLES),
            ("Partially Received", "Mark Received", "Received", MVP_WORKFLOW_ROLES),
            ("Partially Received", "Return to Verification", "In Verification", MVP_WORKFLOW_ROLES),
            ("Partially Received", "Return to Draft", "Draft", MVP_WORKFLOW_ROLES),
            ("Discrepancy Review", "Return to Verification", "In Verification", MVP_WORKFLOW_ROLES),
            ("Discrepancy Review", "Mark Received", "Received", MVP_WORKFLOW_ROLES),
            ("Discrepancy Review", "Return to Draft", "Draft", MVP_WORKFLOW_ROLES),
            ("Received", "Close", "Closed", MVP_WORKFLOW_ROLES),
            ("In Verification", "Close", "Closed", MVP_WORKFLOW_ROLES),
            ("Partially Received", "Close", "Closed", MVP_WORKFLOW_ROLES),
            ("Discrepancy Review", "Close", "Closed", MVP_WORKFLOW_ROLES),
        ],
    },
    {
        "name": "3PL Shipment Request Workflow",
        "document_type": "Three PL Shipment Request",
        "states": ["Submitted", "Draft", "Accepted", "Picking", "Packed", "Shipped", "Closed", "Cancelled"],
        "client_edit_states": ["Draft", "Submitted"],
        "transitions": [
            ("Submitted", "Return to Draft", "Draft", MVP_WORKFLOW_ROLES),
            ("Draft", "Submit", "Submitted", ("3PL Client", *MVP_WORKFLOW_ROLES)),
            ("Submitted", "Accept", "Accepted", MVP_WORKFLOW_ROLES),
            ("Submitted", "Start Picking", "Picking", MVP_WORKFLOW_ROLES),
            ("Accepted", "Start Picking", "Picking", MVP_WORKFLOW_ROLES),
            ("Picking", "Mark Packed", "Packed", MVP_WORKFLOW_ROLES),
            ("Picking", "Mark Shipped", "Shipped", MVP_WORKFLOW_ROLES),
            ("Packed", "Mark Shipped", "Shipped", MVP_WORKFLOW_ROLES),
            ("Shipped", "Close", "Closed", MVP_WORKFLOW_ROLES),
            ("Submitted", "Close", "Closed", MVP_WORKFLOW_ROLES),
            ("Accepted", "Close", "Closed", MVP_WORKFLOW_ROLES),
            ("Picking", "Close", "Closed", MVP_WORKFLOW_ROLES),
            ("Packed", "Close", "Closed", MVP_WORKFLOW_ROLES),
            ("Draft", "Cancel", "Cancelled", ("3PL Client", *MVP_WORKFLOW_ROLES)),
            ("Submitted", "Cancel", "Cancelled", ("3PL Client", *MVP_WORKFLOW_ROLES)),
            ("Accepted", "Cancel", "Cancelled", MVP_WORKFLOW_ROLES),
            ("Picking", "Cancel", "Cancelled", MVP_WORKFLOW_ROLES),
        ],
    },
    {
        "name": "3PL Warehouse Correction Workflow",
        "document_type": "Three PL Warehouse Correction",
        "states": ["Draft", "Applied", "Needs Review", "Cancelled"],
        "transitions": [
            ("Draft", "Apply", "Applied", MVP_WORKFLOW_ROLES),
            ("Draft", "Request Review", "Needs Review", MVP_WORKFLOW_ROLES),
            ("Draft", "Cancel", "Cancelled", MVP_WORKFLOW_ROLES),
            ("Needs Review", "Apply", "Applied", MVP_WORKFLOW_ROLES),
            ("Needs Review", "Return to Draft", "Draft", MVP_WORKFLOW_ROLES),
            ("Needs Review", "Cancel", "Cancelled", MVP_WORKFLOW_ROLES),
        ],
    },
    {
        "name": "3PL Stocktake Session Workflow",
        "document_type": "Three PL Stocktake Session",
        "states": ["Open", "In Progress", "Completed", "Cancelled"],
        "transitions": [
            ("Open", "Start", "In Progress", MVP_WORKFLOW_ROLES),
            ("Open", "Complete", "Completed", MVP_WORKFLOW_ROLES),
            ("In Progress", "Complete", "Completed", MVP_WORKFLOW_ROLES),
            ("Open", "Cancel", "Cancelled", MVP_WORKFLOW_ROLES),
            ("In Progress", "Cancel", "Cancelled", MVP_WORKFLOW_ROLES),
        ],
    },
    {
        "name": "3PL Stocktake Workflow",
        "document_type": "Three PL Stocktake",
        "states": ["Draft", "Applied", "No Difference", "Needs Review", "Cancelled"],
        "transitions": [
            ("Draft", "Apply", "Applied", MVP_WORKFLOW_ROLES),
            ("Draft", "Mark No Difference", "No Difference", MVP_WORKFLOW_ROLES),
            ("Draft", "Request Review", "Needs Review", MVP_WORKFLOW_ROLES),
            ("Draft", "Cancel", "Cancelled", MVP_WORKFLOW_ROLES),
            ("Needs Review", "Apply", "Applied", MVP_WORKFLOW_ROLES),
            ("Needs Review", "Mark No Difference", "No Difference", MVP_WORKFLOW_ROLES),
            ("Needs Review", "Return to Draft", "Draft", MVP_WORKFLOW_ROLES),
            ("Needs Review", "Cancel", "Cancelled", MVP_WORKFLOW_ROLES),
        ],
    },
    {
        "name": "3PL Client Instruction Workflow",
        "document_type": "Three PL Client Instruction",
        "states": ["Submitted", "Reviewed", "Applied", "Closed"],
        "client_edit_states": ["Submitted"],
        "transitions": [
            ("Submitted", "Mark Reviewed", "Reviewed", MVP_WORKFLOW_ROLES),
            ("Submitted", "Apply", "Applied", MVP_WORKFLOW_ROLES),
            ("Reviewed", "Apply", "Applied", MVP_WORKFLOW_ROLES),
            ("Submitted", "Close", "Closed", MVP_WORKFLOW_ROLES),
            ("Reviewed", "Close", "Closed", MVP_WORKFLOW_ROLES),
            ("Applied", "Close", "Closed", MVP_WORKFLOW_ROLES),
        ],
    },
]
